import pandas as pd
import numpy as np

from datasets.dataset_utils import getElectricVehIds
from datasets.dataset_analysis import getTripStats

from SUMO.sumo_utils import mapSUMOVehicleTypes
from SUMO.sumo import runSimulation

# Retrive data about trips from dataset
trips = getTripStats()

# Retrieve SUMO vehicle types map
SUMOvehicleTypes = mapSUMOVehicleTypes(
    hevIds=getElectricVehIds(types=["HEV"]),
    phevIds=getElectricVehIds(types=["PHEV"]),
    evIds=getElectricVehIds(types=["EV"])
)

# Run SUMO simulation and retrieve battery data and other statistics generated by it
SUMOBatteryData, SUMOSimStats = runSimulation(trips, SUMOvehicleTypes, 0)

# Simulation and dataset data comparison
comparisonList = []
for trip in trips.to_dict(orient="records"):
    sumoVehicleId = f"{trip['VehId']}_{trip['Trip']}"

    if sumoVehicleId in SUMOBatteryData:
        sumoEnergy = SUMOBatteryData[sumoVehicleId].totalEnergyConsumed
        datasetEnergy = trip["totalEnergyConsumed"]

        comparisonList.append({
            "id": sumoVehicleId,
            "sumoEnergy": sumoEnergy,
            "datasetEnergy": datasetEnergy,
            "absoluteError": abs(sumoEnergy - datasetEnergy),
            "squaredError": (sumoEnergy - datasetEnergy) ** 2
        })

comparisonData = pd.DataFrame(comparisonList)

# Mean Absolute Error: average absolute difference between SUMO and dataset energy consumption values
MAE = comparisonData["absoluteError"].mean()

# Root Mean Square Error: measures prediction error while penalizing larger deviations more heavily
RMSE = np.sqrt(comparisonData["squaredError"].mean())

# Mean Absolute Percentage Error: average percentage difference between SUMO and dataset energy consumption values
# We filter out records with datasetEnergy at zero so we don't divide by it when calculating MAPE
validDataForMAPE = comparisonData[comparisonData["datasetEnergy"] != 0]

MAPE = (
    validDataForMAPE["absoluteError"] /
    validDataForMAPE["datasetEnergy"]
).mean() * 100

print("MAE:", MAE)
print("RMSE:", RMSE)
print("MAPE:", MAPE, "%")

print("Generated trips:", SUMOSimStats.generatedTrips,
      "Generated vehicles:", SUMOSimStats.generatedVehicles,
      "Simulated vehicles:", SUMOSimStats.simulatedVehicles,
      "Trips discarded:", SUMOSimStats.discardedByDuarouter,
      "Vehicles failed:", SUMOSimStats.failedSimulation)
