import pandas as pd
import numpy as np

from datasets.dataset_analysis import getTripStats
from SUMO.sumo import runSimulation

# Retrive data about trips from dataset
trips = getTripStats()

# Run SUMO simulation and retrieve battery data generated by it
SUMOBatteryData = runSimulation(trips)

# Simulation and dataset data comparison
comparisonList = []
for trip in trips.to_dict(orient="records"):
    sumoVehicleId = f"{trip['VehId']}_{trip['Trip']}"

    if sumoVehicleId in SUMOBatteryData:
        sumoEnergy = SUMOBatteryData[sumoVehicleId].totalEnergyConsumed
        datasetEnergy = trip["totalEnergyConsumed"]

        comparisonList.append({
            "id": sumoVehicleId,
            "sumoEnergy": sumoEnergy,
            "datasetEnergy": datasetEnergy,
            "absoluteError": abs(sumoEnergy - datasetEnergy),
            "squaredError": (sumoEnergy - datasetEnergy) ** 2
        })

comparisonData = pd.DataFrame(comparisonList)

# Mean Absolute Error: average absolute difference between SUMO and dataset energy consumption values
MAE = comparisonData["absoluteError"].mean()

# Root Mean Square Error: measures prediction error while penalizing larger deviations more heavily
RMSE = np.sqrt(comparisonData["squaredError"].mean())

print("MAE:", MAE)
print("RMSE:", RMSE)
