import xml.etree.ElementTree as ET

from SUMO.sumo_paths import CUSTOM, OUTPUT
from SUMO.sumo_types import SUMOTrip, SUMOVehicleExtraData, SUMOBatteryData
from SUMO.sumo_utils import getLanePositionOnEdge, getLanePositionFromEdgeList

# Adds trips to custom.trips.xml
def addSUMOTrips(sumoTrips: list[SUMOTrip]):
    customTripsXml = ET.parse(CUSTOM / "custom.trips.xml")
    routes = customTripsXml.getroot()

    # Clean up previous trip generation if present
    if (routes.findall("trip")):
        for trip in routes.findall("trip"):
            routes.remove(trip)

    # Generate sumo trips
    for sumoTrip in sumoTrips:
        routes.append(ET.Element("trip", {
            "id": sumoTrip.id,
            "type": sumoTrip.type,

            "depart": str(sumoTrip.depart),

            "fromLonLat": sumoTrip.fromLonLat,
            "toLonLat": sumoTrip.toLonLat,

            "departSpeed": str(sumoTrip.startSpeed),
            "arrivalSpeed": str(sumoTrip.endSpeed),
        }))

    customTripsXml.write(
        CUSTOM / "custom.trips.xml",
        encoding="utf-8",
        xml_declaration=True,
    )

# Adds some additional properties to vehicles into custom.rou.xml
def addExtraToSUMOVehicles(vehiclesExtra: dict[str, SUMOVehicleExtraData]):
    customRoutesXml = ET.parse(CUSTOM / "custom.rou.xml")
    routes = customRoutesXml.getroot()

    # Iterate over each vehicle inside routes element
    for vehicle in routes.findall("vehicle"):
        # Retrieve vehicle id and edges that constitutes its route
        sumoVehicleId = vehicle.get("id")
        edges = vehicle.find("route").get("edges").split()

        # Calculate precise departPos as an offset from the begginning of the lane closest to GPS point on the first edge
        departPos = getLanePositionOnEdge(
            vehiclesExtra[sumoVehicleId].startLatitude,
            vehiclesExtra[sumoVehicleId].startLongitude,
            edges[0]
        ).offset

        # Calculate precise arrivalPos as an offset from the begginning of the lane closest to GPS point on the last edge
        arrivalPos = getLanePositionOnEdge(
            vehiclesExtra[sumoVehicleId].endLatitude,
            vehiclesExtra[sumoVehicleId].endLongitude,
            edges[-1]
        ).offset

        # Set calculated departPos and arrivalPos
        vehicle.set("departPos", str(departPos))
        vehicle.set("arrivalPos", str(arrivalPos))

        # Add each stop to the vehicle
        for stop in vehiclesExtra[sumoVehicleId].stops:
            stopLane = getLanePositionFromEdgeList(
                stop["latitude"],
                stop["longitude"],
                edges
            ).lane.getID()

            vehicle.append(
                ET.Element("stop", {
                    "lane": stopLane,
                    "duration": str(stop["duration"])
                })
            )

    customRoutesXml.write(
        CUSTOM / "custom.rou.xml",
        encoding="utf-8",
        xml_declaration=True,
    )

# Returns the duration of the longest trip resulted after a simulation
def getMaxTripDuration():
    tripInfosXml = ET.parse(OUTPUT / "tripinfos.xml")
    tripinfos = tripInfosXml.getroot()

    maxDuration = None

    for tripinfo in tripinfos.findall("tripinfo"):
        if tripinfo.get("id").startswith("pt_"):
            continue

        duration = float(tripinfo.get("duration"))

        if maxDuration is None or duration > maxDuration:
            maxDuration = duration

    return maxDuration if maxDuration is not None else 1000.0

# Reads tripinfos.xml to return resulting battery data generated by a simulation
def readSUMOBatteryOut():
    batteryData: dict[str, SUMOBatteryData] = {}

    tripInfosXml = ET.parse(OUTPUT / "tripinfos.xml")
    tripinfos = tripInfosXml.getroot()

    for tripinfo in tripinfos.findall("tripinfo"):
        tripinfoId = tripinfo.get("id")

        if tripinfoId.startswith("pt_"):
            continue

        batteryData[tripinfoId] = SUMOBatteryData(
            totalEnergyConsumed=float(
                tripinfo.find("battery").get("totalEnergyConsumed")
            )
        )

    return batteryData
