import pandas as pd
import numpy as np

from arguments import args

from data.validation.eVED_data import getElectricVehIds
from data.validation.eVED_analysis import getTripStats

from SUMO.sumo_utils import mapSUMOVehicleTypes
from SUMO.sumo import runSimulation

# Retrive data about trips from dataset
trips = getTripStats()

# Retrieve trajectory ids for both EV and HEV/PHEV trajectories
evTrajectoryIds = trips.loc[
    trips["vehId"].isin(getElectricVehIds(types=["EV"])),
    "trajectoryId"
].tolist()

otherTrajectoryIds = trips.loc[
    trips["vehId"].isin(getElectricVehIds(types=["HEV", "PHEV"])),
    "trajectoryId"
].tolist()

# Retrieve SUMO vehicle types map
SUMOvehicleTypes = mapSUMOVehicleTypes(otherTrajectoryIds, evTrajectoryIds)

# Run SUMO simulation and retrieve battery data and other statistics generated by it
SUMOBatteryData, SUMOSimStats = runSimulation(
    trips, args.depart_delay, SUMOvehicleTypes
)

# Simulation and dataset data comparison
comparisonList = []
for trip in trips.to_dict(orient="records"):
    sumoVehicleId = trip["trajectoryId"]

    if sumoVehicleId in SUMOBatteryData:
        sumoEnergy = SUMOBatteryData[sumoVehicleId].totalEnergyConsumed
        datasetEnergy = trip["totalEnergyConsumed"]

        comparisonList.append({
            "id": sumoVehicleId,
            "sumoEnergy": sumoEnergy,
            "datasetEnergy": datasetEnergy,
            "absoluteError": abs(sumoEnergy - datasetEnergy),
            "squaredError": (sumoEnergy - datasetEnergy) ** 2
        })

comparisonData = pd.DataFrame(comparisonList)

# Mean Absolute Error: average absolute difference between SUMO and dataset energy consumption values
MAE = comparisonData["absoluteError"].mean()

# Root Mean Square Error: measures prediction error while penalizing larger deviations more heavily
RMSE = np.sqrt(comparisonData["squaredError"].mean())

if "HEV" not in args.eved_veh_types and "PHEV" not in args.eved_veh_types:
    # Mean Absolute Percentage Error: average percentage difference between SUMO and dataset energy consumption values
    validDataForMAPE = comparisonData[comparisonData["datasetEnergy"] != 0]

    MAPE = (
        validDataForMAPE["absoluteError"] /
        validDataForMAPE["datasetEnergy"]
    ).mean() * 100
else:
    # Symmetric Mean Absolute Percentage Error: average symmetric percentage difference between SUMO and dataset energy consumption values
    validDataForSMAPE = comparisonData[
        (comparisonData["sumoEnergy"] != 0) |
        (comparisonData["datasetEnergy"] != 0)
    ]

    SMAPE = (
        2 *
        validDataForSMAPE["absoluteError"] /
        (
            validDataForSMAPE["sumoEnergy"].abs() +
            validDataForSMAPE["datasetEnergy"].abs()
        )
    ).mean() * 100

# Print errors esteemation
print("MAE:", MAE)
print("RMSE:", RMSE)

if "HEV" not in args.eved_veh_types and "PHEV" not in args.eved_veh_types:
    print("MAPE:", MAPE, "%")
else:
    print("SMAPE:", SMAPE, "%")

# Print simulation stats
print("Generated trips:", SUMOSimStats.generatedTrips,
      "Generated vehicles:", SUMOSimStats.generatedVehicles,
      "Simulated vehicles:", SUMOSimStats.simulatedVehicles,
      "Trips discarded:", SUMOSimStats.discardedByDuarouter,
      "Vehicles failed:", SUMOSimStats.failedSimulation)
