import pandas as pd
import numpy as np

from arguments import args

from data.validation.eVED_data import getElectricVehIds
from data.validation.eVED_analysis import getTripStats

from SUMO.sumo_utils import mapSUMOVehicleTypes
from SUMO.sumo import runSimulation

from virtual_data.simulation_results import printSimulationStats, printValidationErrors

def runSUMOvalidation():
    # Retrive data about trips from dataset
    trips = getTripStats()

    # Retrieve trajectory ids for both EV and HEV/PHEV trajectories
    EVTrajectoryIds = trips.loc[
        trips["vehId"].isin(getElectricVehIds(types=["EV"])),
        "trajectoryId"
    ].tolist()

    otherTrajectoryIds = trips.loc[
        trips["vehId"].isin(getElectricVehIds(types=["HEV", "PHEV"])),
        "trajectoryId"
    ].tolist()

    # Retrieve SUMO vehicle types map
    SUMOvehicleTypes = mapSUMOVehicleTypes(
        otherTrajectoryIds, EVTrajectoryIds, randomize=args.random_veh_types
    )

    # Run SUMO simulation and retrieve battery data and other statistics generated by it
    SUMOBatteryData, SUMOSimStats = runSimulation(
        trips, args.depart_delay, SUMOvehicleTypes
    )

    # Simulation and dataset data comparison
    comparisonList = []
    for trip in trips.to_dict(orient="records"):
        sumoVehicleId = trip["trajectoryId"]

        if sumoVehicleId in SUMOBatteryData:
            sumoEnergy = SUMOBatteryData[sumoVehicleId].totalEnergyConsumed
            datasetEnergy = trip["totalEnergyConsumed"]

            comparisonList.append({
                "id": sumoVehicleId,
                "sumoEnergy": sumoEnergy,
                "datasetEnergy": datasetEnergy,
                "absoluteError": abs(sumoEnergy - datasetEnergy),
                "squaredError": (sumoEnergy - datasetEnergy) ** 2
            })

    comparisonData = pd.DataFrame(comparisonList)

    # Mean Absolute Error: average absolute difference between SUMO and dataset energy consumption values
    MAE = comparisonData["absoluteError"].mean()

    # Root Mean Square Error: measures prediction error while penalizing larger deviations more heavily
    RMSE = float(np.sqrt(comparisonData["squaredError"].mean()))

    # Calculate MAPE or SMAPE based on vehicle types used for validation
    if "HEV" in args.eved_veh_types or "PHEV" in args.eved_veh_types:
        validData = comparisonData[
            (comparisonData["sumoEnergy"] != 0) |
            (comparisonData["datasetEnergy"] != 0)
        ]

        MAPE = None

        # Symmetric Mean Absolute Percentage Error: average symmetric percentage difference between SUMO and dataset energy consumption values
        SMAPE = (
            2 *
            validData["absoluteError"] /
            (
                validData["sumoEnergy"].abs() +
                validData["datasetEnergy"].abs()
            )
        ).mean() * 100
    else:
        validData = comparisonData[comparisonData["datasetEnergy"] != 0]

        # Mean Absolute Percentage Error: average percentage difference between SUMO and dataset energy consumption values
        MAPE = (
            validData["absoluteError"] /
            validData["datasetEnergy"]
        ).mean() * 100

        SMAPE = None

    # Print validation errors
    printValidationErrors(MAE, RMSE, MAPE, SMAPE)

    # Print simulation stats
    printSimulationStats(SUMOSimStats)
